title: Fanghao Chen
tagline: Fanghao Chen. Jinan University. Development Economics. Urban Economics. Industrial Organization. International Economics. Faculty. Assistant Professor.
logo: /assets/img/leisure.jpg
description: I'm an Assistant Professor of Economics in the School of Economics at Jinan University.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
