title: Fanghao Chen
tagline: Fanghao Chen. PhD. National School of Development of Peking University. Urban Economics. Industrial Organization. Development Economics. Multinational Enterprises. Faculty. Professor.
logo: /assets/img/formal3.jpg
description: I'm a PhD candidate in economics in National School of Development at Peking University.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
