title: Fanghao Chen
tagline: Fanghao Chen. PhD. National School of Development of Peking University. Urban Economics. Industrial Organization. Development Economics. Multinational Enterprises. Faculty. Professor.
logo: /assets/img/ccer.jpg
description: I'm a economics PhD candidate at Peking University, National School of Development (formerly known as CCER)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
